apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-sample
  template:
    metadata:
      labels:
        app: flask-sample
    spec: 
      containers:
      - name: flask-sample
        image: kenlai212/flask-sample:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-sample-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask-sample