apiVersion: apps/v1
kind: Deployment
metadata:
  name: biosentvec-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biosentvec-api
  template:
    metadata:
      labels:
        app: biosentvec-api
    spec: 
      containers:
      - name: biosentvec-api
        image: kenlai212/biosentvec-api:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: biosentvec-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: biosentvec-api